theme: theme
title: Builds
author: Jason Morley
email: support@jbmorley.co.uk
description: GitHub Actions Status Board
platforms: Mac, iPhone and iPad
baseurl: ""
url: "https://builds.jbmorley.co.uk"
repository: https://github.com/inseven/builds
copyright: 2021-2026 <a href="https://jbmorley.co.uk/about">Jason Morley</a>

navigation:
  - title: Builds
    href: /
  - title: Releases
    href: /releases
  - title: GitHub
    href: https://github.com/inseven/builds
  - title: More
    href: https://jbmorley.co.uk/software

footer:
  - title: Privacy Policy
    href: /privacy-policy

destination: ../_site

defaults:
  - values:
      layout: "page"
